# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot


class Ui_FrmMenu(object):
    def setupUi(self, FrmMenu):
        FrmMenu.setObjectName("FrmMenu")
        FrmMenu.resize(1245, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmMenu.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FrmMenu)
        self.centralwidget.setObjectName("centralwidget")
        FrmMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FrmMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1245, 21))
        self.menubar.setObjectName("menubar")
        self.menuEncriptar = QtWidgets.QMenu(self.menubar)
        self.menuEncriptar.setObjectName("menuEncriptar")
        self.menuDesencriptar = QtWidgets.QMenu(self.menubar)
        self.menuDesencriptar.setObjectName("menuDesencriptar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        FrmMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrmMenu)
        self.statusbar.setObjectName("statusbar")
        FrmMenu.setStatusBar(self.statusbar)
        self.actionAyuda = QtWidgets.QAction(FrmMenu)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionSalir = QtWidgets.QAction(FrmMenu)
        self.actionSalir.setObjectName("actionSalir")
        self.actionDesencriptar_Archivo = QtWidgets.QAction(FrmMenu)
        self.actionDesencriptar_Archivo.setObjectName("actionDesencriptar_Archivo")
        self.actionEncriptar_Archivo = QtWidgets.QAction(FrmMenu)
        self.actionEncriptar_Archivo.setObjectName("actionEncriptar_Archivo")
        self.menubar.addAction(self.menuEncriptar.menuAction())
        self.menubar.addAction(self.menuDesencriptar.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(FrmMenu)
        QtCore.QMetaObject.connectSlotsByName(FrmMenu)

    def retranslateUi(self, FrmMenu):
        _translate = QtCore.QCoreApplication.translate
        FrmMenu.setWindowTitle(_translate("FrmMenu", "Sistema de Encriptación de Datos"))
        self.menuEncriptar.setTitle(_translate("FrmMenu", "Encriptar"))
        self.menuDesencriptar.setTitle(_translate("FrmMenu", "Desencriptar"))
        self.menuOpciones.setTitle(_translate("FrmMenu", "Opciones"))
        self.actionAyuda.setText(_translate("FrmMenu", "Ayuda"))
        self.actionSalir.setText(_translate("FrmMenu", "Salir"))
        self.actionDesencriptar_Archivo.setText(_translate("FrmMenu", "Desencriptar Archivo"))
        self.actionEncriptar_Archivo.setText(_translate("FrmMenu", "Encriptar Archivo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmMenu = QtWidgets.QMainWindow()
    ui = Ui_FrmMenu()
    ui.setupUi(FrmMenu)
    FrmMenu.show()
    sys.exit(app.exec_())
